// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsuAhJgGP67o5Og7DzWldLSu5rna03kAU',
    appId: '1:1087112296673:web:c1492352d0f9ffbe8b1fa0',
    messagingSenderId: '1087112296673',
    projectId: 'jupiter-9e44a',
    authDomain: 'jupiter-9e44a.firebaseapp.com',
    storageBucket: 'jupiter-9e44a.firebasestorage.app',
    measurementId: 'G-9QQKBFN9EM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDENiY61Qi5VbFmkpUoGcDxycRmbB9eBL8',
    appId: '1:1087112296673:android:1e101fd6f40bae1f8b1fa0',
    messagingSenderId: '1087112296673',
    projectId: 'jupiter-9e44a',
    storageBucket: 'jupiter-9e44a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACfl_xIU-00KlkOiEQ22mKwWoVIhwKvLE',
    appId: '1:1087112296673:ios:49e03a53db2d237f8b1fa0',
    messagingSenderId: '1087112296673',
    projectId: 'jupiter-9e44a',
    storageBucket: 'jupiter-9e44a.firebasestorage.app',
    iosBundleId: 'com.example.jupiter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACfl_xIU-00KlkOiEQ22mKwWoVIhwKvLE',
    appId: '1:1087112296673:ios:49e03a53db2d237f8b1fa0',
    messagingSenderId: '1087112296673',
    projectId: 'jupiter-9e44a',
    storageBucket: 'jupiter-9e44a.firebasestorage.app',
    iosBundleId: 'com.example.jupiter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsuAhJgGP67o5Og7DzWldLSu5rna03kAU',
    appId: '1:1087112296673:web:e83df563ea53b6dc8b1fa0',
    messagingSenderId: '1087112296673',
    projectId: 'jupiter-9e44a',
    authDomain: 'jupiter-9e44a.firebaseapp.com',
    storageBucket: 'jupiter-9e44a.firebasestorage.app',
    measurementId: 'G-B7XB6DDG75',
  );
}
